---
- hosts: default 
  vars:
    username: vagrant
    home: "/home/{{ username }}"
    src_home: "{{ home }}/repos"
  user: "{{ username }}"
  tasks:
    - name: "create folder {{ item }}"
      file: 
        path: "{{ item }}" 
        state: directory
      with_items:
        - "{{ src_home }}"
        - "{{ home }}/.m2"
        - "{{ home }}/.IdeaIC2017.2"
    - name: update apt-get for sublime
      shell: 'echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list'
    - name: add extra apt-get repositories 
      apt_repository:
        repo: "{{ item }}"
      become: true
      become_user: root
      with_items:
        - 'ppa:fish-shell/release-2'
        - 'ppa:openjdk-r/ppa'
    - name: Install libraries with apt
      apt: 
        name: "{{ item }}"
        update_cache: yes
        allow_unauthenticated: yes
      become: true
      become_user: root
      with_items:
        - maven
        - default-jdk 
        - git
        - libcurl4-openssl-dev
        - libexpat1-dev
        - tcl-dev
        - gettext
        - libssl-dev
        - sublime-text
        - fish
        - openjdk-7-jdk
        - silversearcher-ag
        - vim
        - vagrant
        - virtualbox
    - name: extract git # clone git???? what version do I check out?
      unarchive:
        src: https://github.com/git/git/archive/v2.14.0.tar.gz 
        dest: "{{ src_home }}"
        remote_src: yes
    - name: install latest version
      shell: make; make install
      args:
        chdir: "{{ src_home }}/git-2.14.0"
    - name: clone my dotfiles
      git:
        dest: "{{ home }}/.config"
        repo: https://github.com/ethomev/.config.git
    - name: download intellij
      unarchive:
        src: https://download.jetbrains.com/idea/ideaIC-2017.2.5.tar.gz # extract version to a variable?
        dest: /opt
        remote_src: yes
      become: true
      become_user: root
    - name: pull down my notes
      git:
        dest: "{{ src_home }}/myNotes"
        repo: https://github.com/ethomev/myNotes.git 
    - name: copy settings.xml file for maven
      copy:
        src: settings.xml
        dest: "{{ home }}/.m2/settings.xml"
    - name: intellij config
      unarchive:
        src: intellij-config.tar.gz
        dest: "{{ home }}/.IdeaIC2017.2/"
