---
- hosts: default # This will change to localhost and I will need to add entry to ansible hosts file
  user: vagrant # this will change to ethomev
  vars:
    home: /home/vagrant # ethomev
    src_home: /home/vagrant/repos # ethomev
  tasks:
    - name: create src folder
      file: 
        path: "{{ src_home }}" 
        state: directory
    - name: update apt-get for sublime
      shell: 'echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list'
    - name: add fish ppa
      apt_repository:
        repo: 'ppa:fish-shell/release-2'
      become: true
      become_user: root
    - name: Install libraries with apt
      apt: 
        name: "{{ item }}"
        update_cache: yes
        allow_unauthenticated: yes
      become: true
      become_user: root
      with_items:
        - maven
        - default-jdk 
        - git
        - libcurl4-openssl-dev
        - libexpat1-dev
        - tcl-dev
        - gettext
        - libssl-dev
        - sublime-text
        - fish
    - name: extract git
      unarchive:
        src: https://github.com/git/git/archive/v2.14.0.tar.gz 
        dest: "{{ src_home }}"
        remote_src: yes
    - name: install latest version
      shell: make; make install
      args:
        chdir: "{{ src_home }}/git-2.14.0"
    - name: get my git config
      shell: curl https://raw.githubusercontent.com/ethomev/.configuration/master/.gitconfig --create-dirs -o ~/.config/git/config
    - name: get my gitignore file
      shell: curl https://raw.githubusercontent.com/ethomev/.configuration/master/.gitignore --create-dirs -o ~/.config/git/ignore
    - name: get dmitry's fish config
      shell: curl https://raw.githubusercontent.com/dmi3/bin/master/config/fish/config.fish --create-dirs -o ~/.config/fish/config.fish
    - name: download intellij
      unarchive:
        src: https://download.jetbrains.com/idea/ideaIC-2017.2.5.tar.gz # extract version to a variable?
        dest: /opt
        remote_src: yes
      become: true
      become_user: root
    - name: pull down my notes
      git:
        dest: "{{ src_home }}/myNotes"
        repo: https://github.com/ethomev/myNotes.git 
    - name: copy settings.xml file for maven
      copy:
        src: settings.xml
        dest: "{{ home }}/.m2/settings.xml"
